#!/usr/bin/env python3
import sys
from analyzer import Analyzer
import application
import helpers

def main():
    # only screen-name as an argument
    if len(sys.argv) != 2:
        sys.exit("usage: ./tweets @username")
    
    screen_name = sys.argv[1].strip("@")
    
    # get all recent tweets
    tweetList = helpers.get_user_timeline(screen_name, 50)
    
    if tweetList==None:
        sys.exit("Invalid username")
    
    # absolute path to list
    positive = os.path.join(sys.path[0], "positive-words.txt")
    negative = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer 
    analyzer = Analyzer(positive, negative)
    
    for tweet in tweetList:
        print(tweet)
        score = analyzer.analyze(tweet)
        print("score={}".format(score))
        
        if score > 0.0:
            print(colored(":)", "green"))
        elif score < 0.0:
            print(colored(":(", "red"))
        else:
            print(colored(":|", "yellow"))
        
if __name__ == "__main__":
    main()